services:
  accountsdb:
    container_name: accountsdb
    environment:
      MYSQL_DATABASE: accountsdb
    ports:
      - "3306:3306"
    extends:
      file: common-config.yaml
      service: microservice-db-config

  cardsdb:
    image: mysql
    container_name: cardsdb
    environment:
      MYSQL_DATABASE: cardsdb
    ports:
      - "3308:3306"
    extends:
      file: common-config.yaml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    environment:
      MYSQL_DATABASE: loansdb
    ports:
      - "3307:3306"
    extends:
      file: common-config.yaml
      service: microservice-db-config

  configserver:
    image: "amitkrgkp/configserver:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config

  accounts:
    image: "amitkrgkp/accounts:s7"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    depends_on:
      accountsdb:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  loans:
    image: "amitkrgkp/loans:s7"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    depends_on:
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  cards:
    image: "amitkrgkp/cards:s7"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    depends_on:
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: bridge