services:
  accountsdb:
    container_name: accountsdb
    environment:
      MYSQL_DATABASE: accountsdb
    ports:
      - "3306:3306"
    extends:
      file: common-config.yaml
      service: microservice-db-config

  cardsdb:
    image: mysql
    container_name: cardsdb
    environment:
      MYSQL_DATABASE: cardsdb
    ports:
      - "3308:3306"
    extends:
      file: common-config.yaml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    environment:
      MYSQL_DATABASE: loansdb
    ports:
      - "3307:3306"
    extends:
      file: common-config.yaml
      service: microservice-db-config

  #  loansdb1:
  #    container_name: loansdb1
  #    environment:
  #      MYSQL_DATABASE: loansdb
  #    ports:
  #      - "3309:3306"
  #    extends:
  #      file: common-config.yaml
  #      service: microservice-db-config

  configserver:
    image: "amitkrgkp/configserver:s9"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config

  eurekaserver:
    image: "amitkrgkp/eurekaserver:s9"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    extends:
      file: common-config.yaml
      service: microservice-base-config

  accounts:
    image: "amitkrgkp/accounts:s9"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  loans:
    image: "amitkrgkp/loans:s9"
    container_name: loans-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      loansdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  #  loans1:
  #    image: "amitkrgkp/loans:s9"
  #    container_name: loans-ms1
  #    ports:
  #      - "8091:8090"
#    healthcheck:
#      test: "curl --fail --silent localhost:8091/actuator/health/readiness | grep UP || exit 1"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 10s
  #    depends_on:
  #      loansdb1:
  #        condition: service_healthy
  #    environment:
  #      SPRING_APPLICATION_NAME: "loans"
  #      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb1:3306/loansdb"
  #    extends:
  #      file: common-config.yaml
  #      service: microservice-configserver-config

  cards:
    image: "amitkrgkp/cards:s9"
    container_name: cards-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  gatewayserver:
    image: "amitkrgkp/gatewayserver:s9"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: bridge